version: '3.4'

services:
  backendapi:
    image: backendapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 7878:7878
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - appLogs:/usr/src/app/appLogs
    restart: always
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - inventorydb:/data/db
    restart: always
    environment:
      MONGO_INITDB_DATABASE:  inventoryTracking
    command: mongod --quiet --logpath /dev/null

volumes:
  appLogs:
  inventorydb:
